### PR TITLE
[Documentation] Add first version of FAQ file

### LINKED ISSUE #65: Create a FAQ Section for CofiBlocks Documentation
Description:

To improve the user experience and address common questions, we need to create a Frequently Asked Questions (FAQ) section in the documentation. This section will help new developers, community members, and contributors quickly find answers to their questions without having to search through the entire documentation or raise issues.

Objectives:

1. Address Common Questions
- Include questions related to CofiBlocks’ purpose, setup, features, and contributions.
- Provide detailed and concise answers for each question.
2. Organize for Accessibility
- Structure the FAQ in categories (e.g., General, Technical, Community, Contribution).
- Link relevant sections of the documentation to the answers for further details.

Be creative!

### PR DESCRIPTION
**Pull request by EmmanuelAR**
## Description

Adding FAQ file readme
Close #65 

## Checklist

- [x] The title of the PR is clear and descriptive.
- [x] All tests have been run and passed.
- [x] Code follows project conventions (Biome formatting, linting).
- [x] Documentation has been updated as needed.
- [x] Commit messages follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) style.

## Type of Change

- [ ] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Chore
- [x] Documentation
- [ ] Test

### Manual Testing
N/A

### Automated Tests
- [ ] Unit tests added or updated
- [ ] Integration tests added or updated
- [ ] E2E tests added or updated

## Additional Notes
Captura de pantalla 2024-11-22 a la(s) 10 15 43 p  m

### CODE REVIEW

**Comment by EmmanuelAR** [comment]
Hello team :)

Heres the first version of the FAQ readme, please share me the current questions that the team received, let me know to add it!

@evgongora

**Review by evgongora — CHANGES_REQUESTED** [review]
Could you please address the next changes:

- Remove these 2 questions from the readme and add them here?

https://github.com/Vagabonds-Labs/cofiblocks?tab=readme-ov-file#-what-is-a-collaborative-business
https://github.com/Vagabonds-Labs/cofiblocks?tab=readme-ov-file#-how-does-it-work

-Can you add a link to all these questions inside the readme
- Create a question for this 

https://github.com/Vagabonds-Labs/cofiblocks?tab=readme-ov-file#-join-the-community
https://github.com/Vagabonds-Labs/cofiblocks?tab=readme-ov-file#-development-resources

**Comment by EmmanuelAR** [comment]
Fixed @evgongora, let me know!

**Review by evgongora — APPROVED** [review]
LGTM! Thank you so much

**Pull request merged**
