### PR TITLE
Extract shared order filtering logic into custom hook

### LINKED ISSUE #57: Refactor Order Management Logic into Custom Hook
## Extract shared order management logic into custom hook

**Description:**

The `my-orders `and `my-sales` pages contain significant duplicate logic for filtering, searching, and state management. We should extract this into reusable hooks.

Code References:

### `my-orders`
```
export default function MyOrders() {
	const [searchTerm, setSearchTerm] = useState("");
	const [isFiltersModalOpen, setIsFiltersModalOpen] = useState(false);
	const [filteredOrders, setFilteredOrders] = useState(mockedOrders);
	const [activeFilters, setActiveFilters] = useState<FormValues>({});
	const router = useRouter();

	const openFiltersModal = () => {
		setIsFiltersModalOpen(true);
	};

	const closeFiltersModal = () => {
		setIsFiltersModalOpen(false);
	};

	const { control, handleSubmit } = useForm<FormValues>({
		resolver: zodResolver(filtersSchema),
		defaultValues: {
			statusPaid: false,
			statusPrepared: false,
			statusShipped: false,
			statusDelivered: false,
		},
	});

	const onSubmit = (data: FormValues) => {
		console.log(data);
		setActiveFilters(data);
		closeFiltersModal();
	};

	const handleItemClick = (id: string) => {
		router.push(`/user/my-orders/${id}`);
	};

	useEffect(() => {
		const newFilteredOrders = mockedOrders
			.map((orderGroup) => ({
				...orderGroup,
				items: orderGroup.items.filter((item) => {
					const matchesSearch = searchTerm
						? item.sellerName.toLowerCase().includes(searchTerm.toLowerCase())
						: true;

					const activeStatusFilters = [
						activeFilters.statusPaid,
						activeFilters.statusPrepared,
						activeFilters.statusShipped,
						activeFilters.statusDelivered,
					];

					const matchesStatus = activeStatusFilters.some(Boolean)
						? (activeFilters.statusPaid &&
								item.status === SalesStatusEnum.Paid) ??
							(activeFilters.statusPrepared &&
								item.status === SalesStatusEnum.Prepared) ??
							(activeFilters.statusShipped &&
								item.status === SalesStatusEnum.Shipped) ??
							(activeFilters.statusDelivered &&
								item.status === SalesStatusEnum.Delivered)
						: true;

					return matchesSearch && matchesStatus;
				}),
			}))
			.filter((orderGroup) => orderGroup.items.length > 0);

		if (!searchTerm && !Object.values(activeFilters).some(Boolean)) {
			setFilteredOrders(mockedOrders);
		} else {
			setFilteredOrders(newFilteredOrders);
		}
	}, [searchTerm, activeFilters]);
```

### `my-sales`
```
export default function MySales() {
	const [searchTerm, setSearchTerm] = useState("");
	const [isFiltersModalOpen, setIsFiltersModalOpen] = useState(false);
	const [filteredOrders, setFilteredOrders] = useState(mockedOrders);
	const [activeFilters, setActiveFilters] = useState<FormValues>({});
	const router = useRouter();

	const openFiltersModal = () => {
		setIsFiltersModalOpen(true);
	};

	const closeFiltersModal = () => {
		setIsFiltersModalOpen(false);
	};

	const { control, handleSubmit } = useForm<FormValues>({
		resolver: zodResolver(filtersSchema),
		defaultValues: {
			statusPaid: false,
			statusPrepared: false,
			statusShipped: false,
			statusDelivered: false,
			deliveryAddress: false,
			deliveryMeetup: false,
		},
	});

	const onSubmit = (data: FormValues) => {
		console.log(data);
		setActiveFilters(data);
		closeFiltersModal();
	};

	const handleItemClick = (id: string) => {
		router.push(`/user/my-sales/${id}`);
	};

	useEffect(() => {
		const newFilteredOrders = mockedOrders
			.map((orderGroup) => ({
				...orderGroup,
				items: orderGroup.items.filter((item) => {
					const matchesSearch = searchTerm
						? item.buyerName.toLowerCase().includes(searchTerm.toLowerCase())
						: true;

					const activeStatusFilters = [
						activeFilters.statusPaid,
						activeFilters.statusPrepared,
						activeFilters.statusShipped,
						activeFilters.statusDelivered,
					];

					const matchesStatus = !activeStatusFilters.some(Boolean)
						? true
						: (activeFilters.statusPaid &&
								item.status === SalesStatusEnum.Paid) ??
							(activeFilters.statusPrepared &&
								item.status === SalesStatusEnum.Prepared) ??
							(activeFilters.statusShipped &&
								item.status === SalesStatusEnum.Shipped) ??
							(activeFilters.statusDelivered &&
								item.status === SalesStatusEnum.Delivered);

					const activeDeliveryFilters = [
						activeFilters.deliveryAddress,
						activeFilters.deliveryMeetup,
					];

					const matchesDelivery = !activeDeliveryFilters.some(Boolean)
						? true
						: (activeFilters.deliveryAddress &&
								item.delivery === DeliveryMethodEnum.Address) ??
							(activeFilters.deliveryMeetup &&
								item.delivery === DeliveryMethodEnum.Meetup);

					return matchesSearch && matchesStatus && matchesDelivery;
				}),
			}))
			.filter((orderGroup) => orderGroup.items.length > 0);

		if (!searchTerm && !Object.values(activeFilters).some(Boolean)) {
			setFilteredOrders(mockedOrders);
		} else {
			setFilteredOrders(newFilteredOrders);
		}
	}, [searchTerm, activeFilters]);
```

Acceptance Criteria:

- Create a shared hook for order filtering that works for both My Orders and My Sales:
- Supports multiple simultaneous filters (status, delivery method)
- Search works across seller/buyer names
- Empty states are handled appropriately

### PR DESCRIPTION
**Pull request by derianrddev**
## Description

Closes #57  

1. **Created a custom hook (`useOrderFiltering`):**
   - All logic related to filtering, searching, and state management for orders has been extracted and consolidated into a reusable custom hook. 
   - This reduces duplication and improves code maintainability.

2. **Centralized types into a single file:**
   - A dedicated file was created to centralize `interfaces`, `enums`, and `types` related to orders.
   - This ensures consistency across the codebase and avoids duplicated logic in different files.

3. **Fixed filtering logic (`useEffect`):**
   - The filtering logic was updated because the `??` operator did not correctly evaluate `false` boolean states.
   - Now, all filters (statuses and delivery methods) are properly considered.

## Checklist

- [X] The title of the PR is clear and descriptive.
- [X] All tests have been run and passed.
- [X] Code follows project conventions (Biome formatting, linting).
- [X] Documentation has been updated as needed.
- [X] Commit messages follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) style.

## Type of Change

- [ ] Bugfix
- [ ] Feature
- [X] Refactor
- [ ] Chore
- [ ] Documentation
- [ ] Test

## Additional Notes

https://www.loom.com/share/b23e6fc857e6494e81fe69723e1687e5?sid=4cbcf37c-214d-48ba-88bb-5a36b974136c

Thank you for the opportunity to contribute to this project.

### CODE REVIEW

**Review by evgongora — CHANGES_REQUESTED** [review]
Hey @derianrddev! Thank you so much, everything looks really good just one thing, could you please run Biome format by doing `bun run format`?

**Comment by derianrddev** [comment]
image

**Comment by derianrddev** [comment]
> Hey @derianrddev! Thank you so much, everything looks really good just one thing, could you please run Biome format by doing `bun run format`?

image

**Comment by derianrddev** [comment]
> Hey @derianrddev! Thank you so much, everything looks really good just one thing, could you please run Biome format by doing `bun run format`?

image

**Comment by evgongora** [comment]
Awesome work! Thank you so much :)

**Review by evgongora — APPROVED** [review]

**Pull request merged**
