### PR TITLE
Refactor Order Status Management

### LINKED ISSUE #59: Refactor Order Status Management
Description:

The ProductStatusDetails component is too complex and handles multiple responsibilities. It needs to be split into smaller, focused components.

Code Reference: `ProductStatusDetails`

Acceptance Criteria:

- Split into smaller components:
- Implement proper prop typing for each component
- Add loading states for status updates
- Handle error states appropriately

### PR DESCRIPTION
**Pull request by jimenezz22**
## Description

Closes #59 

This pull request introduces a modular refactor for managing order status in the ProductStatusDetails component, improving readability, maintainability, and scalability. Below are the highlights of the changes made to each modified file.

### 1. ProductStatusDetails.tsx
- Integrated the newly created StatusBanner, ProductDetailsList, and StatusUpdateModal components to modularize the logic.
- Simplified state handling and reduced inline logic for better readability.
- Updated Type Handling, explicitly typed StatusStepsEnum and aligned its usage across the application.
- Eliminated unused variables like openOrderStatusModal and optimized type imports.
### 2. StatusBanner.tsx
- Encapsulates the logic for displaying order status banners.
Dynamically renders messages for both producers and customers based on orderStatus and isProducer props.
- Added StatusBannerProps to enforce clarity and prevent runtime errors.
### 3. ProductDetailsList.tsx
- Extracted the logic for displaying product details (e.g., roast, type, quantity) into a reusable component.
- Rendered details using a flexible array of objects to allow dynamic additions.
### 4. StatusUpdateModal.tsx
- Handles the logic for updating order status through a modal interface.
- Integrated with react-hook-form to manage the form state and validation.
- Replaced any with precise types like FormEvent<HTMLFormElement> to comply with TypeScript linting rules.
- Updated onSubmit and control props to work seamlessly with StatusStepsEnum.

## Checklist

- [ ] The title of the PR is clear and descriptive.
- [ ] All tests have been run and passed.
- [ ] Code follows project conventions (Biome formatting, linting).
- [ ] Documentation has been updated as needed.
- [ ] Commit messages follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) style.

## Type of Change

- [ ] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Chore
- [ ] Documentation
- [ ] Test

### Automated Tests
- [ ] Unit tests added or updated
- [ ] Integration tests added or updated
- [ ] E2E tests added or updated

### CODE REVIEW

**Review by evgongora — CHANGES_REQUESTED** [review]
Awesome work @jimenezz22! Could you just run biome format pls? :)

**Comment by jimenezz22** [comment]
> Awesome work @jimenezz22! Could you just run biome format pls? :)

Screenshot 2024-11-29 at 9 43 02 AM

**Comment by jimenezz22** [comment]
> > Awesome work @jimenezz22! Could you just run biome format pls? :)
> 
> Screenshot 2024-11-29 at 9 43 02 AM

bun run build

Screenshot 2024-11-29 at 9 44 28 AM

**Comment by evgongora** [comment]
All clean, good to go!

**Review by evgongora — APPROVED** [review]

**Pull request merged**
