### PR TITLE
[feat] Add complete UI translation and localize components (EN, ES, PT)

### LINKED ISSUE #55: Complete UI Translation
## Description
Ensure all missing strings in the UI are translated into **English**, **Spanish**, and **Portuguese** using the existing Next.js i18n setup.

## Steps
1. **Audit UI Strings**:
   - Identify all untranslated or hardcoded strings across the project.
   - Cross-check with the existing translation files (`public/locales/en`, `public/locales/es`, `public/locales/pt`).

2. **Add Missing Strings**:
   - Add missing keys to the respective JSON files for:
     - **English** (`en`)
     - **Spanish** (`es`)
     - **Portuguese** (`pt`)
   - Ensure key names are descriptive and follow the established naming conventions.

3. **Implement Translations**:
   - Replace hardcoded strings in the codebase with the `t` function from `next-i18next`.
   - Use placeholders and context handling for dynamic strings.

4. **Test Translations**:
   - Verify that translations are displayed correctly for **English**, **Spanish**, and **Portuguese**.
   - Use the language toggle feature (if available) to test switching between languages.

## Acceptance Criteria
- No untranslated strings remain in the UI.
- All translations are correctly reflected in **English**, **Spanish**, and **Portuguese**.
- Codebase is free from hardcoded UI strings.
- The website functions seamlessly when switching languages.

## Additional Notes
- The default language should remain **English**.
- Ensure translation keys are consistent and meaningful.
- Refer to [Next.js i18n Documentation](https://nextjs.org/docs/advanced-features/i18n-routing) for guidance.

---

### PR DESCRIPTION
**Pull request by LazarusAA**
### Overview

This pull request addresses issue #55 by ensuring all missing strings in the UI are translated into English, Spanish, and Portuguese using the existing Next.js i18n setup.

#### Audit UI Strings

- Identified all untranslated or hardcoded strings across the project by thoroughly reviewing each component and page.
- Cross-checked with existing translation files (`public/locales/en`, `public/locales/es`, `public/locales/pt`) to ensure consistency and completeness.

#### Add Missing Strings

- Added missing translation keys to the `en.json`, `es.json`, and `pt.json` files.
- Ensured key names are descriptive and follow the established naming conventions for clarity and maintainability.

#### Implement Translations

- Replaced all hardcoded strings in the codebase with the `t` function from `next-i18next`.
- Utilized placeholders and context handling for dynamic strings to ensure accurate translations in various contexts.

#### Test Translations

- Verified that all translations are displayed correctly for English, Spanish, and Portuguese.
- Used the language toggle feature to test switching between languages without any issues.

### Issue Reference

Closes #55

### Additional Notes

- **Default Language:** The application continues to default to English.
- **Translation Keys:** All keys are consistent with naming conventions and are meaningful for easy reference.
- **Documentation Reference:** Followed guidelines from the [Next.js i18n Documentation](https://nextjs.org/docs/advanced-features/i18n-routing).
- **Merge Conflicts:** Successfully merged updates from `main` with no conflicts.
- **Portuguese Translations:** Used reliable translation tools for Portuguese translations; feedback from native speakers is appreciated to ensure accuracy.
- **Open to Feedback:** Ready to make any necessary adjustments based on reviewer suggestions.

### CODE REVIEW

**Comment by LazarusAA** [comment]
### Test Translations
https://github.com/user-attachments/assets/55d017b1-b2f8-4c20-a7bf-bb8d1e337e70

**Comment by LazarusAA** [comment]
I have resolved the latest merge conflicts and pushed the changes. Everything should now be up to date with the main branch. Please review and let me know if there are any further issues or feedback. Thanks!

**Review by evgongora — COMMENTED** [review]
Awesome job! Please just run bun run format and we're good to go :)

**Review by evgongora — APPROVED** [review]
Thank you so much!

**Pull request merged**
